Autodelete summary nodes later if it would change the moved node index
Bad node view child components: missing node for component 2
2, org.freeplane.view.swing.map.NodeView[,207,8,111x115,layout=org.freeplane.view.swing.map.SelectableLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
1, org.freeplane.view.swing.map.NodeView[,0,0,111x115,layout=org.freeplane.view.swing.map.SelectableLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
, org.freeplane.view.swing.map.NodeView[,226,8,111x115,layout=org.freeplane.view.swing.map.SelectableLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
org.freeplane.view.swing.map.MainView[,50,50,190x36,alignmentX=0.5,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=CENTER,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=summary-test,verticalAlignment=CENTER,verticalTextPosition=TOP]
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for
length 2
	at org.freeplane.view.swing.map.VerticalNodeViewLayoutStrategy.calculateLayoutY(VerticalNodeViewLayoutStrategy.java:144)
	at org.freeplane.view.swing.map.VerticalNodeViewLayoutStrategy.calculateLayoutData(VerticalNodeViewLayoutStrategy.java:111)
	at org.freeplane.view.swing.map.VerticalNodeViewLayoutStrategy.calculateLayoutData(VerticalNodeViewLayoutStrategy.java:105)
	at org.freeplane.view.swing.map.NodeViewLayout.layoutContainer(NodeViewLayout.java:44)
	at org.freeplane.view.swing.map.SelectableLayout.layoutContainer(SelectableLayout.java:40)